version: "3.7"
services:
  triple-db:
    image: mariadb:10.3
    ports:
      - "13306:3306"
    environment:
      - MARIADB_DATABASE=triple
      - MARIADB_ROOT_PASSWORD=root-pass
      - MARIADB_USER=triple
      - MARIADB_PASSWORD=1234
      - TZ=Asia/Seoul
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./mysql:/var/lib/mysql
